# Generated by Django 6.0 on 2025-12-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password1', models.CharField(blank=True, max_length=15, null=True)),
                ('calorie_goal', models.IntegerField(blank=True, null=True)),
                ('protein_goal', models.IntegerField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='profile_image/')),
            ],
        ),
    ]
