# Generated by Django 6.0 on 2026-01-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='food_image/'),
        ),
    ]
