# Generated by Django 6.0 on 2026-01-17 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_meallog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='foods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.food'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meallog',
            name='food',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
