# Generated by Django 6.0 on 2026-01-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_meallog_foods_alter_meallog_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meallog',
            name='food',
        ),
    ]
