# Generated by Django 6.0 on 2026-01-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_meallog_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meallog',
            old_name='foods',
            new_name='food',
        ),
    ]
