# Generated by Django 6.0 on 2026-01-17 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rename_foods_meallog_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.user'),
        ),
    ]
