# Generated by Django 6.0 on 2026-01-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_meallog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='food_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
