# Generated by Django 6.0 on 2026-01-23 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_meallog_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.food'),
        ),
    ]
