# Generated by Django 6.0 on 2026-01-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_favoritefood'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
