# Generated by Django 6.0 on 2026-01-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_food_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
    ]
