# Generated by Django 6.0 on 2026-01-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_remove_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
